config/routes.rb
Rails.application.routes.draw do

  resources :notes
  get '/my' => 'home#my'
  root 'home#top'
  get '/about' => 'home#about'
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @message = "ようこそGatebookへ！"
  end

  def about
  end

  def my
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.all
  end

  def show
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to @note, notice: "投稿が保存されました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to @note, notice: "投稿が更新されました"
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private

    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/home/about.html.erb
<h1>サイト紹介</h1>
<p>当サイトは自己啓発本オタクの管理人Zeusが「引き寄せの法則」を実践・報告するブログです。</p>
<h1>なぜLEXUS?</h1>
<p>金持ちになりたい、高級車を持ちたい、という思いの中で出会ったLEXUS。<br>LEXUSに乗っている人たちはどのような人たちでしょうか？<br>一流のステータスを持ち、駐車場つきのいい家に住み、助手席には美しいパートナーの女性を乗せているような人物、のように思っています。<br>私は「LEXUS」を通して自分の求めるありとあらゆるものを得ることができるのでは、という仮説を立て、検証していくことに決めました。</p>
<h1>理念</h1>
<p>〜Wintreprener × Wintertainer〜
<br>人がワクワクして、夢を語り合える、互いに幸福なソリューションを提供し続ける<br>
<br>レクサスを所有するにふさわしい人間、それは人を喜ばせ、夢を自由に語り合える環境を作り出せる人間であると
<br>私は信じています。
<br>この信念のもとに、レクサスを所有する、という私自身がワクワクする夢に向かって
<br>取り組んでいくことを誓います。</p>

app/views/home/my.html.erb
<h1>管理人ページ</h1>
<h1>善意ある方は触らないでね☆<br>※勉強不足により管理人ページのみを<br>ユーザー認証にすることができませんでしたm(_ _)m</h1>
<li><%= link_to "新規ブログ", new_note_path %></li>

app/views/home/top.html.erb
  <div class="top-wrapper">
    <div class="container">
      <h1>Journey to LEXUS<br>I'll reach there.</h1>
    </div>
  </div>
  <div class="brank-white">
    <h1>     </h1>
  </div>
  <div class="lesson-wrapper">
      <div class="heading">
        <h1>Profile</h1>
        <h2>Zeus<br>都内某大学<br>起業家・投資家を志す<br>趣味はバイク・ベース・雑談</h2>
      </div>
  </div>
  <div class="brank-white">
    <h1>     </h1>
  </div>
  <div class="message-wrapper">
    <div class="container">
      <div class="heading2">
        <h1>引き寄せの法則とLEXUSが紡ぐ物語</h1>
        <h2>We can create our own future.</h2>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Journey to LEXUS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar">
    <div class="container">
      <div id="logo"><%= link_to "Journey to LEXUS", my_path %></div>
      <ul class="header-right">
        <li><%= link_to "Top", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Blogs", notes_path %></li>
      </ul>
    </div>
  </header>

  <div class="container">
    <%= yield %>
  </div>

  <div class="container">
    <footer class="footer">
      &copy; 2016 Zeus, Inc.
    </footer>
  </div>
</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @note.errors.count %>件のエラーがあります。</h2>

      <ul>
        <% @note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  タイトル
  <%= f.text_field :title, { class: "form-control title-field" } %>
  内容
  <%= f.text_area :content, { class: "form-control content-field" } %>
  <%= f.submit "保存", { class: "btn primary-btn" } %>
<% end %>

app/views/notes/_note.html.erb
<li>
  <span class="content">
    <%= link_to note.title, note_path(note.id) %>
  </span>
</li>

app/views/notes/edit.html.erb
<h1>投稿を編集する</h1>
<%= render 'form' %>

app/views/notes/index.html.erb
<h1>Blogs</h1>
<ul class="notes">
  <%= render @notes %>
</ul>

app/views/notes/new.html.erb
<h1>新規投稿する</h1>
<%= render 'form' %>

app/views/notes/show.html.erb
<p id="notice" class="alert alert-success"><%= notice %></p>

<h2>タイトル</h2>
<p><%= simple_format(@note.title) %></p>
<h2>内容</h2>
<p><%= simple_format(@note.content) %></p>

<!--編集がいるときのみ表示-->

<!--<%= link_to "編集", edit_note_path(@note.id), class: "btn edit-btn" %>
<%= link_to "削除", note_path(@note.id), method: "delete", class: "btn destroy-btn", "data-confirm" => "本当に削除しますか？" %>-->